version: '3.8'

services:
  
  backend:
    image: backend_image  
    container_name: backend
    build:
      context: ./backend  
    ports:
      - "8000:8000" 
    env_file:
      - .env  
   
  frontend:
    image: frontend_image  
    container_name: frontend
    build:
      context: ./frontend  
    ports:
      - "8080:80"  
  
    depends_on:
      - backend  
